<?php
$basePath = dirname(__dir__) . DIRECTORY_SEPARATOR;

require_once $basePath . 'vendor/autoload.php';

$app = App\App::getInstance();
$app->setStartTime();
$app::load();

$app->getRouter($basePath)
    ->get('/', 'Site#index', 'home')
    ->post('/', 'Site#index', 'subscribe')
    ->get('/contact', 'Site#contact', 'contact')
    ->post('/contact', 'Site#contact', 'contact2')
    ->get('/cgv', 'Site#cgv', 'cgv')
    ->get('/mentions', 'Site#mentions', 'mentions')
    //BOUTIQUE
    ->get('/order', 'orders#order', 'order')
    ->get('/orders/[i:id_user]-[i:id_order]', 'orders#show', 'my_order')
    ->get('/shop/confirmation', 'orders#confirmation', 'confirmation')
    ->post('/shop/confirmation', 'orders#confirmation', 'post_confirmation')
    ->post('/shop/add', 'shop#basket', 'add_basket')
    ->post('/shop/update', 'shop#updateBasket', 'update_basket')
    ->get('/shop/update', 'shop#updateBasket', 'update_basket2')
    ->post('/shop/delete', 'shop#deleteLine', 'delete_basket')
    ->post('/shop/choice', 'shop#choice', 'choice_address')
    //UTILISATEUR
    ->get('/register', 'user#register', 'register')
    ->post('/register', 'user#register', 'register2')
    ->get('/check/[*:token]-[i:id]', 'user#checking', 'checking')
    ->get('/connect', 'user#connect', 'connect')
    ->post('/connect', 'user#connect', 'connect2')
    ->get('/profile', 'user#profile', 'profile')
    ->post('/profile', 'user#profile', 'profile2')
    ->post('/profile/add', 'usersInfos#createUserInfos', 'add_address')
    ->get('/profile/address/[i:user_id]-[i:id]', 'usersInfos#updateUserInfos', 'user_address')
    ->post('/profile/address/[i:user_id]-[i:id]', 'usersInfos#updateUserInfos', 'post_user_address')
    ->get('/profile/address/[i:user_id]-[i:id]/delete', 'usersInfos#deleteUserInfos', 'user_address_delete')
    ->get('/logout', 'user#logout', 'logout')
    //BLOG
    ->get('/posts', 'post#all', 'posts')
    ->get('/post/[*:slug]-[i:id]', 'post#show', 'post')
    ->post('/post/[*:slug]-[i:id]', 'post#comment', 'comment')
    ->get('/beers', 'beer#all', 'beers')
    ->get('/beer/[*:slug]-[i:id]', 'beer#show', 'beer')
    ->get('/categories', 'category#all', 'categories')
    ->get('/category/[*:slug]-[i:id]', 'category#show', 'category')
    //ADMINISTRATION
    ->get('/admin', 'admin\Admin#index', 'admin')
    ->get('/admin/posts', 'admin\Admin#posts', 'admin_posts')
    ->get('/admin/beers', 'admin\Admin#beers', 'admin_beers')
    ->get('/admin/orders', 'admin\Admin#orders', 'admin_orders')
    ->get('/admin/categories', 'admin\Admin#categories', 'admin_categories')
    ->get('/admin/users', 'admin\Admin#users', 'admin_users')
    ->get('/admin/posts/[*:slug]-[i:id]', 'admin\PostEdit#PostEdit', 'admin_posts_edit')
    ->post('/admin/posts/[*:slug]-[i:id]', 'admin\PostEdit#postUpdate', 'admin_post_update')
    ->get('/admin/post-delete/[*:slug]-[i:id]', 'admin\PostEdit#postDelete', 'admin_post_delete')
    ->get('/admin/postInsert', 'admin\PostEdit#postInsert', 'admin_post_insert')
    ->post('/admin/postInsert', 'admin\PostEdit#postInsert', 'admin_post_insert2')
    ->get('/admin/category/[*:slug]-[i:id]', 'admin\CategoryEdit#categoryEdit', 'admin_category_edit')
    ->get('/admin/category-delete/[*:slug]-[i:id]', 'admin\CategoryEdit#categoryDelete', 'admin_category_delete')
    ->post('/admin/category/[*:slug]-[i:id]', 'admin\CategoryEdit#categoryUpdate', 'admin_category_update')
    ->get('/admin/categoryInsert', 'admin\CategoryEdit#categoryInsert', 'admin_category_insert')
    ->post('/admin/categoryInsert', 'admin\CategoryEdit#categoryInsert', 'admin_category_insert2')
    ->get('/admin/user/[*:lastname]-[i:id]', 'admin\UserEdit#userEdit', 'admin_user_edit')
    ->get('/admin/user-delete/[*:lastname]-[i:id]', 'admin\UserEdit#userDelete', 'admin_user_delete')
    ->post('/admin/user/[*:lastname]-[i:id]', 'admin\UserEdit#userUpdate', 'admin_user_update')
    ->get('/admin/beer/[*:slug]-[i:id]', 'admin\BeerEdit#beerEdit', 'admin_beer_edit')
    ->get('/admin/beer-delete/[*:slug]-[i:id]', 'admin\BeerEdit#beerDelete', 'admin_beer_delete')
    ->post('/admin/beer/[*:slug]-[i:id]', 'admin\BeerEdit#beerUpdate', 'admin_beer_update')
    ->get('/admin/beerInsert', 'admin\BeerEdit#beerInsert', 'admin_beer_insert')
    ->post('/admin/beerInsert', 'admin\BeerEdit#beerInsert', 'admin_beer_insert2')
    ->get('/admin/orders/[i:id]-[i:id]', 'admin\OrderEdit#orderEdit', 'admin_order_edit')
    ->get('/admin/order-delete/[i:id]-[i:id]', 'admin\OrderEdit#orderDelete', 'admin_order_delete')
    ->run();
